# Generated by Django 3.2.12 on 2022-02-14 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nutrient', models.IntegerField(choices=[(1, 'białko'), (2, 'tłuszcz'), (3, 'węglowodan'), (4, 'woda'), (5, 'inne')])),
                ('glycemic_index', models.IntegerField(choices=[(1, 'Niski index(<55)'), (2, 'Średni index(56-69)'), (3, 'Wysoki index(>70)')])),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammage', models.IntegerField(help_text='w gramach')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 'bardzo prosty'), (2, 'prosty'), (3, 'średniozaawansowany'), (4, 'zaawansowany'), (5, 'trudny')], default=1)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_app.cuisine')),
                ('ingredient', models.ManyToManyField(through='diet_app.IngredientRecipe', to='diet_app.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.IntegerField(choices=[(1, 'Śniadanie'), (2, 'Drugie śniadanie'), (3, 'Obiad'), (4, 'Podwieczorek'), (5, 'Kolacja'), (6, 'Przekąska')])),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_plan',
            field=models.ManyToManyField(through='diet_app.RecipeMealPlan', to='diet_app.MealPlan'),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.recipe'),
        ),
    ]
